verbose: false

reporting:
#  print: summary
#    reports:
#      - lcov
  dir: ./reports/coverage
  watermarks:
#      statements: [50, 80]
#      lines: [50, 80]
#      functions: [50, 80]
      branches: [50, 60]

instrumentation:
    root: .
#    default-excludes: true
    excludes:

hooks:
#  hook-run-in-context: false
#  post-require-hook: null
  handle-sigint: true
check:
    global:
        statements: 100
        lines: 100
        branches: 90
        functions: 100

#    each:
#        statements: 0
#        lines: 0
#        branches: 0
#        functions: 0
#        excludes: []